jwt:
  secret: 6c3cf93a5c2988f5cace02954e9fe7a6e02089cebdc196564361e93ab8f1d62a

spring:
  application:
    name: auth

  datasource:
#    url: jdbc:postgresql://localhost:6432/auth
#    username: admin
#    password: 123
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath*:database/initDB.sql

  jpa:
    database: postgresql
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG